# Set theme
#remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- CODE_OF_CONDUCT.md
- LICENSE
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 5
paginate_path: projects/page:num


# 4. Jekyll settings
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Amsterdam # Timezone for blog posts and alike



# Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
url: 'https://tudelft-cda-lab.github.io/'
baseurl: ''
title: 'Cyber Data Analytics Lab'
description: 'Webpage for the Cyber Data Analytics Lab'
permalink: pretty
logo: "/assets/TUD.png"
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference


# Header nav
navigation_header:
- title: Home
  url: /
- title: People
  url: /people/
- title: Projects
  url: /projects/
- title: Publications
  url: /publications/
- title: Contact
  url: /contact/


# Footer nav
#navigation_footer:
#- title: back to top 
#  url: "#top"

# Collections
collections:
- posts:
    title: Research projects
    output: true
    feature_image: "https://picsum.photos/2560/600?image=866"
- papers:
    title: Publication list
    output: true
    feature_image: "https://picsum.photos/2560/600?image=866"
 
# ---------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------
# Update this collecting for adding/removing roles 
roles:
- r: leader
- r: postdoc
- r: phd
- r: external  

# Update this collection for adding/removing people
people:
- name: Sicco Verwer
  pic: sicco.jpg # Picture file name
  role: leader
  position: Assistant Professor (PI)
  social:
    - title: twitter
      url: https://twitter.com/siccoverwer
    - title: globe
      url: https://www.tudelft.nl/staff/s.e.verwer/

- name: Christian Hammerschmidt
  pic: male-no.png
  role: postdoc
  position: Postdoctoral Researcher
  social:
    - title: twitter
      url: https://twitter.com/chrshmmmr
    - title: globe
      url: https://www.tudelft.nl/en/staff/c.a.hammerschmidt/
      
- name: Laurens Bliek
  pic: male-no.png
  role: postdoc
  position: Postdoctoral Researcher
  social:
    - title: twitter
      url: #
    - title: globe
      url: https://www.tudelft.nl/en/staff/l.bliek/
    
- name: Azqa Nadeem
  pic: azqa.jpg
  role: phd
  position: PhD Candidate
  social:
    - title: twitter
      url: https://twitter.com/azqa_nadeem
    - title: globe
      url: https://www.tudelft.nl/staff/azqa.nadeem/
      
- name: Daniel Vos
  pic: male-no.png
  role: phd
  position: PhD Candidate
  social:
    - title: twitter
      url: #
    - title: globe
      url: #
      
- name: Mark Patrick Roeling
  pic: male-no.png
  role: phd
  position: PhD Candidate
  social:
    - title: twitter
      url: https://twitter.com/mproeling
    - title: globe
      url: #
      
- name: Sofia Tsoni
  pic: female-no.png
  role: external
  position: Developer
  social:
    - title: twitter
      url: #
    - title: globe
      url: #

# ---------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------

# Postal address
address: Van Mourik Broekmanweg 6, 2628 XE Delft

# ---------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------


# 6. Jekyll collections settings
defaults: 
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
      

