# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://tudelft-cda-lab.github.io/'
baseurl: ''
title: 'Cyber Data Analytics Lab'
description: 'Webpage for the Cyber Data Analytics Lab'
permalink: pretty
logo: "/assets/TUD.png"

# Pagination
paginate: 5
paginate_path: projects/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: People
  url: /team/
- title: Projects
  url: /projects/
- title: Contact
  url: /contact/


# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Research projects
    output: true
    feature_image: "https://picsum.photos/2560/600?image=866"
    
# Team names, titles and social links
people:
- name: Sicco Verwer
  pic: m-1
  position: Lab Head
  social:
    - title: twitter
      url: #
    - title: website
      url: #

- name: Christian Hammerschmidt
  pic: m-2
  position: Post Doc
  social:
    - title: twitter
      url: #
    - title: website
      url: #
      
- name: Laurens Bliek
  pic: m-3
  position: Post Doc
  social:
    - title: twitter
      url: #
    - title: website
      url: #
    
- name: Azqa Nadeem
  pic: f-1
  position: PhD candiate
  social:
    - title: twitter
      url: #
    - title: website
      url: #
      
- name: Daniel Vos
  pic: m-4
  position: PhD candiate
  social:
    - title: twitter
      url: #
    - title: website
      url: #
      
- name: Sofia Tsoni
  pic: f-1
  position: Developer
  social:
    - title: twitter
      url: #
    - title: website
      url: #

