# Set theme
#remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- CODE_OF_CONDUCT.md
- LICENSE
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 5
paginate_path: projects/page:num
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: #DavidDarnes # jekyll-seo-tag > Owners twitter username
#author: DavidDarnes # jekyll-seo-tag > default author
#social: # jekyll-seo-tag > social overrides
#  name: David Darnes # jekyll-seo-tag > real name
#  links:  # jekyll-seo-tag > social aliases (sameAs)
#    - https://twitter.com/DavidDarnes
#    - https://www.facebook.com/daviddarnes
#    - https://www.linkedin.com/in/daviddarnes
#    - https://github.com/daviddarnes
markdown: kramdown
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Amsterdam # Timezone for blog posts and alike



# Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
url: 'https://tudelft-cda-lab.github.io/'
baseurl: ''
title: 'Cyber Data Analytics Lab'
description: 'Webpage for the Cyber Data Analytics Lab'
permalink: pretty
logo: "/assets/TUD.png"
repo: "https://github.com/daviddarnes/alembic"
#email: "me@daviddarnes.com"
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference


# Header nav
navigation_header:
- title: Home
  url: /
- title: People
  url: /people/
- title: Projects
  url: /projects/
- title: Contact
  url: /contact/


# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Research projects
    output: true
    feature_image: "https://picsum.photos/2560/600?image=866"
    
# Team names, titles and social links
people:
- name: Sicco Verwer
  pic: m-1
  position: Lab Head
  social:
    - title: twitter
      url: https://twitter.com/
    - title: globe
      url: https://google.com/

- name: Christian Hammerschmidt
  pic: m-2
  position: Post Doc
  social:
    - title: twitter
      url: https://twitter.com/
    - title: globe
      url: https://google.com/
      
- name: Laurens Bliek
  pic: m-3
  position: Post Doc
  social:
    - title: twitter
      url: https://twitter.com/
    - title: globe
      url: https://google.com/
    
- name: Azqa Nadeem
  pic: f-1
  position: PhD candiate
  social:
    - title: twitter
      url: https://twitter.com/
    - title: globe
      url: https://google.com/
      
- name: Daniel Vos
  pic: m-4
  position: PhD candiate
  social:
    - title: twitter
      url: https://twitter.com/
    - title: globe
      url: https://google.com/
      
- name: Sofia Tsoni
  pic: f-1
  position: Developer
  social:
    - title: twitter
      url: https://twitter.com/
    - title: globe
      url: https://google.com/

# 6. Jekyll collections settings
defaults: 
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
      
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

