# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://tudelft-cda-lab.github.io/'
baseurl: ''
title: 'Cyber Data Analytics Lab'
description: 'Webpage for the Cyber Data Analytics Lab'
permalink: pretty
logo: "/assets/TUD.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: People
  url: /people/
- title: Projects
  url: /blog/
- title: Contact
  url: /contact/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "Project descriptions"
    feature_text: |
      Research work
    feature_image: "https://picsum.photos/2560/600?image=866"

